[functions.store-application-logs]
enabled = true
verify_jwt = true
import_map = "./functions/store-application-logs/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/store-application-logs/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/store-application-logs/*.html" ]

[functions.chat-conversations]
enabled = true
verify_jwt = true
import_map = "./functions/chat-conversations/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat-conversations/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-conversations/*.html" ]

[functions.response-conversations]
enabled = true
verify_jwt = true
import_map = "./functions/response-conversations/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/response-conversations/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/response-conversations/*.html" ]

[functions.create-vector-store]
enabled = true
verify_jwt = true
import_map = "./functions/openai/create-vector-store/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai/create-vector-store/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-vector-store/*.html" ]

[functions.upload-file]
enabled = true
verify_jwt = true
import_map = "./functions/openai/upload-file/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai/upload-file/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/openai/upload-file/*.html" ]

[functions.add-file-to-vector-store]
enabled = true
verify_jwt = true
import_map = "./functions/openai/add-file-to-vector-store/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai/add-file-to-vector-store/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-file-to-vector-store/*.html" ]
